spring:
  application:
    name: springofmsc
  datasource:
    # Master-Slave 설정
    master:
      url: jdbc:mysql://127.0.0.1:33061/msc_database?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
      username: app_master
      password: 1234
      driver-class-name: com.mysql.cj.jdbc.Driver
    slave:
      url: jdbc:mysql://127.0.0.1:33062/msc_database?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
      username: app_slave
      password: 1234
      driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
